# colors
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

# bindings
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# shift + alt + (h,l) to navigate between windows
bind -n M-H previous-window
bind -n M-L next-window

# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# vim navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# theme
set -g @plugin "janoamaral/tokyo-night-tmux"

# battery info
set -g @tokyo-night-tmux_show_battery_widget 1
set -g @tokyo-night-tmux_battery_name "BAT1"
set -g @tokyo-night-tmux_battery_low_threshold 21 # default

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
