# tmux autostart
if [ "$TMUX" = "" ]; then tmux; fi

# english utf-8 by default
export LC_ALL=en_US.UTF-8

# for signing git commits
export GPG_TTY=$(tty)

# use starship
eval "$(starship init zsh)"

# aliases
alias vi=nvim
alias vim=nvim


# Plugin manager
source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# autosugesstions commands
antigen bundle zsh-users/zsh-autosuggestions

# nvm lazy loading
export NVM_LAZY_LOAD=true
antigen bundle lukechilds/zsh-nvm

antigen apply

