# english by default
export LC_ALL=C

# for signing git commits
export GPG_TTY=$(tty)

source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# autosugesstions commands
antigen bundle zsh-users/zsh-autosuggestions

# nvm lazy loading
export NVM_LAZY_LOAD=true
antigen bundle lukechilds/zsh-nvm

antigen apply
